<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="André van Zyl">
<meta name="dcterms.date" content="2023-11-24">

<title>PyStats</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="PyStats_files/libs/clipboard/clipboard.min.js"></script>
<script src="PyStats_files/libs/quarto-html/quarto.js"></script>
<script src="PyStats_files/libs/quarto-html/popper.min.js"></script>
<script src="PyStats_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PyStats_files/libs/quarto-html/anchor.min.js"></script>
<link href="PyStats_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PyStats_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PyStats_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PyStats_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PyStats_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup"><span class="header-section-number">1</span> Setup</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages"><span class="header-section-number">1.1</span> Packages</a></li>
  <li><a href="#functions" id="toc-functions" class="nav-link" data-scroll-target="#functions"><span class="header-section-number">1.2</span> Functions</a></li>
  </ul></li>
  <li><a href="#population-proportion" id="toc-population-proportion" class="nav-link" data-scroll-target="#population-proportion"><span class="header-section-number">2</span> Population Proportion</a>
  <ul class="collapse">
  <li><a href="#one-proportion" id="toc-one-proportion" class="nav-link" data-scroll-target="#one-proportion"><span class="header-section-number">2.1</span> One Proportion</a>
  <ul class="collapse">
  <li><a href="#estimating-population-proportion" id="toc-estimating-population-proportion" class="nav-link" data-scroll-target="#estimating-population-proportion"><span class="header-section-number">2.1.1</span> Estimating Population Proportion</a></li>
  <li><a href="#sample-size-determination" id="toc-sample-size-determination" class="nav-link" data-scroll-target="#sample-size-determination"><span class="header-section-number">2.1.2</span> Sample Size Determination</a></li>
  </ul></li>
  <li><a href="#two-proportions" id="toc-two-proportions" class="nav-link" data-scroll-target="#two-proportions"><span class="header-section-number">2.2</span> Two Proportions</a>
  <ul class="collapse">
  <li><a href="#estimating-a-difference-in-population-proportions" id="toc-estimating-a-difference-in-population-proportions" class="nav-link" data-scroll-target="#estimating-a-difference-in-population-proportions"><span class="header-section-number">2.2.1</span> Estimating a Difference in Population Proportions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#population-means" id="toc-population-means" class="nav-link" data-scroll-target="#population-means"><span class="header-section-number">3</span> Population Means</a>
  <ul class="collapse">
  <li><a href="#one-mean" id="toc-one-mean" class="nav-link" data-scroll-target="#one-mean"><span class="header-section-number">3.1</span> One Mean</a></li>
  <li><a href="#mean-difference-for-paired-data" id="toc-mean-difference-for-paired-data" class="nav-link" data-scroll-target="#mean-difference-for-paired-data"><span class="header-section-number">3.2</span> Mean Difference for Paired Data</a>
  <ul class="collapse">
  <li><a href="#using-scipy-and-statsmodels" id="toc-using-scipy-and-statsmodels" class="nav-link" data-scroll-target="#using-scipy-and-statsmodels"><span class="header-section-number">3.2.1</span> Using SciPy and StatsModels</a></li>
  </ul></li>
  <li><a href="#estimating-a-difference-in-population-means-for-independent-groups" id="toc-estimating-a-difference-in-population-means-for-independent-groups" class="nav-link" data-scroll-target="#estimating-a-difference-in-population-means-for-independent-groups"><span class="header-section-number">3.3</span> Estimating a Difference in Population Means for Independent Groups</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question"><span class="header-section-number">3.3.1</span> Research Question</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#end" id="toc-end" class="nav-link" data-scroll-target="#end"><span class="header-section-number">4</span> End</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="PyStats.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PyStats</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>André van Zyl </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 24, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="setup" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Setup</h1>
<section id="packages" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="packages"><span class="header-section-number">1.1</span> Packages</h2>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display, Math</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sympy <span class="im">import</span> latex, symbols, diff</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.precision'</span>, <span class="dv">2</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>np.set_printoptions(precision<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>random.seed(<span class="dv">1738</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="functions" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="functions"><span class="header-section-number">1.2</span> Functions</h2>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> round_values(numbers, precision):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Rounds a list of numbers to a given precision.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">    numbers (list of float): The list of numbers to round.</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">    precision (int): The number of decimal places to round each number to.</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">    list of float: The list of rounded numbers.</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [<span class="bu">round</span>(num, precision) <span class="cf">for</span> num <span class="kw">in</span> numbers]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="population-proportion" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Population Proportion</h1>
<section id="one-proportion" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="one-proportion"><span class="header-section-number">2.1</span> One Proportion</h2>
<section id="estimating-population-proportion" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="estimating-population-proportion"><span class="header-section-number">2.1.1</span> Estimating Population Proportion</h3>
<p>A sample of 659 parents with a toddler was taken and asked if they used a car seat for all travel with their toddler. 540 parents responded ‘yes’ to this question. Calcualte the proportion and 95% CIs</p>
<section id="normal-approximation-method" class="level4" data-number="2.1.1.1">
<h4 data-number="2.1.1.1" class="anchored" data-anchor-id="normal-approximation-method"><span class="header-section-number">2.1.1.1</span> Normal Approximation Method</h4>
<p><span class="math display">\[
\hat{p} \pm z \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}
\]</span></p>
<p>Breaking it down:</p>
<ul>
<li><span class="math inline">\(\hat{p}\)</span> represents the sample proportion.</li>
<li><span class="math inline">\(z\)</span> is the z-score corresponding to the confidence level (1.96 for 95% confidence).</li>
<li><span class="math inline">\(n\)</span> is the sample size.</li>
<li>The square root term <span class="math inline">\(\sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}\)</span> calculates the standard error of the sample proportion.</li>
</ul>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Given data</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>count <span class="op">=</span> <span class="dv">540</span>  <span class="co"># number of parents who responded 'yes'</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>nobs <span class="op">=</span> <span class="dv">659</span>   <span class="co"># total number of parents asked</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the proportion</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>proportion <span class="op">=</span> count <span class="op">/</span> nobs</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion as per the new information</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> proportion</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Total number of parents surveyed</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> nobs</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Z-score for 95% confidence</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> <span class="fl">1.96</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> np.sqrt(p_hat <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p_hat) <span class="op">/</span> n)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the 95% confidence interval using the given formula</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="op">=</span> p_hat <span class="op">-</span> z <span class="op">*</span> se</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>ci_upper <span class="op">=</span> p_hat <span class="op">+</span> z <span class="op">*</span> se</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>round_values([p_hat, ci_lower, ci_upper], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>[0.82, 0.79, 0.85]</code></pre>
</div>
</div>
</section>
<section id="exact-binomial-method" class="level4" data-number="2.1.1.2">
<h4 data-number="2.1.1.2" class="anchored" data-anchor-id="exact-binomial-method"><span class="header-section-number">2.1.1.2</span> Exact (Binomial) Method</h4>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.proportion <span class="im">import</span> proportion_confint</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the 95% confidence interval for the proportion</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 'binom_test' is used for exact CI calculation appropriate for binomial distribution</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>ci_low, ci_upp <span class="op">=</span> proportion_confint(count, nobs, alpha<span class="op">=</span><span class="fl">0.05</span>, method<span class="op">=</span><span class="st">'binom_test'</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>round_values([proportion, ci_low, ci_upp], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>[0.82, 0.79, 0.85]</code></pre>
</div>
</div>
</section>
</section>
<section id="sample-size-determination" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="sample-size-determination"><span class="header-section-number">2.1.2</span> Sample Size Determination</h3>
<section id="normal-approximation-method-1" class="level4" data-number="2.1.2.1">
<h4 data-number="2.1.2.1" class="anchored" data-anchor-id="normal-approximation-method-1"><span class="header-section-number">2.1.2.1</span> Normal Approximation Method</h4>
<p><span class="math display">\[MoE = \frac{{1}}{\sqrt{n}}\]</span></p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>moe <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">232</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>moe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>0.06565321642986127</code></pre>
</div>
</div>
<section id="for-95-confidence" class="level5" data-number="2.1.2.1.1">
<h5 data-number="2.1.2.1.1" class="anchored" data-anchor-id="for-95-confidence"><span class="header-section-number">2.1.2.1.1</span> For 95% Confidence</h5>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Margin of Error (MoE)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>MoE <span class="op">=</span> <span class="fl">0.03</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the sample size using the simplified formula from the image</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># n = (1 / MoE)^2</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> (<span class="dv">1</span> <span class="op">/</span> MoE)<span class="op">**</span><span class="dv">2</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># The sample size should be a whole number</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="bu">int</span>(<span class="bu">round</span>(sample_size))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>sample_size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>1111</code></pre>
</div>
</div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Margin of Error (MoE)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>MoE <span class="op">=</span> <span class="fl">0.03</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the sample size using the simplified formula from the image</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># n = (1 / MoE)^2</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> (<span class="dv">1</span> <span class="op">/</span> MoE)<span class="op">**</span><span class="dv">2</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># The sample size should be a whole number</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="bu">int</span>(<span class="bu">round</span>(sample_size))</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>sample_size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>1111</code></pre>
</div>
</div>
</section>
<section id="for-99-confidence" class="level5" data-number="2.1.2.1.2">
<h5 data-number="2.1.2.1.2" class="anchored" data-anchor-id="for-99-confidence"><span class="header-section-number">2.1.2.1.2</span> For 99% Confidence</h5>
<p><span class="math display">\[
\begin{align*}
&amp; \hat{p} \pm Z^* \cdot \frac{1}{2\sqrt{n}} \\
&amp; MoE = Z^* \cdot \frac{1}{2\sqrt{n}} \\
&amp; n = \left( \frac{Z^*}{2 \cdot MoE} \right)^2 \\
\end{align*}
\]</span></p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Values provided in the image</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>Z_star <span class="op">=</span> <span class="fl">2.576</span>  <span class="co"># Z-score for 99% confidence</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>MoE <span class="op">=</span> <span class="fl">0.03</span>      <span class="co"># Margin of Error</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size calculation</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> (Z_star <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> MoE)) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Since sample size must be a whole number, round up</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>n_rounded <span class="op">=</span> math.ceil(n)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(n_rounded)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1844</code></pre>
</div>
</div>
</section>
</section>
<section id="exact-method" class="level4" data-number="2.1.2.2">
<h4 data-number="2.1.2.2" class="anchored" data-anchor-id="exact-method"><span class="header-section-number">2.1.2.2</span> Exact Method</h4>
<p><span class="math inline">\(n = \left( \frac{Z_{\alpha/2} \times \sqrt{p(1-p)}}{MoE} \right)^2\)</span></p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Desired margin of error</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>margin_of_error <span class="op">=</span> <span class="fl">0.04</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># For a 95% confidence interval, the z-score is approximately 1.96</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> norm.ppf(<span class="fl">0.975</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Since the population proportion is unknown, we use the most conservative estimate, p = 0.5</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> p</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the sample size using the formula for margin of error</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> (z_score <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> p <span class="op">*</span> q) <span class="op">/</span> (margin_of_error <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Since sample size must be a whole number, we round up</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="bu">int</span>(sample_size) <span class="op">+</span> <span class="dv">1</span> <span class="cf">if</span> sample_size <span class="op">%</span> <span class="dv">1</span> <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="bu">int</span>(sample_size)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>sample_size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>601</code></pre>
</div>
</div>
<p>What minimum sample size does the researcher need in order to create a 98% conservative confidence interval with a margin of error of no more than 3%?</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Desired margin of error</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>margin_of_error <span class="op">=</span> <span class="fl">0.03</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># For a 98% confidence interval, the z-score is approximately 2.33 (found using the ppf function)</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> norm.ppf(<span class="fl">0.99</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Since the population proportion is unknown, we use the most conservative estimate, p = 0.5</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> p</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the sample size using the formula for margin of error</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> (z_score <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> p <span class="op">*</span> q) <span class="op">/</span> (margin_of_error <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Since sample size must be a whole number, we round up</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="bu">int</span>(sample_size) <span class="op">+</span> (sample_size <span class="op">%</span> <span class="dv">1</span> <span class="op">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>sample_size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>1504</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="two-proportions" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="two-proportions"><span class="header-section-number">2.2</span> Two Proportions</h2>
<section id="estimating-a-difference-in-population-proportions" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="estimating-a-difference-in-population-proportions"><span class="header-section-number">2.2.1</span> Estimating a Difference in Population Proportions</h3>
<p><span class="math display">\[
\begin{align*}
\text{Best Estimate} \pm \text{MoE} \\
\hat{p}_1 - \hat{p}_2 \pm 1.96 \cdot \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}
\end{align*}
\]</span></p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Given sample sizes and number of successes</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>n1, x1 <span class="op">=</span> <span class="dv">988</span>, <span class="dv">543</span> <span class="co"># sample of white children</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>n2, x2 <span class="op">=</span> <span class="dv">247</span>, <span class="dv">91</span>  <span class="co"># sample of black children</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the sample proportions</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>p1 <span class="op">=</span> x1 <span class="op">/</span> n1</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>p2 <span class="op">=</span> x2 <span class="op">/</span> n2</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error for the difference in proportions</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> np.sqrt(p1 <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p1) <span class="op">/</span> n1 <span class="op">+</span> p2 <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p2) <span class="op">/</span> n2)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the z-score for 95% confidence</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> norm.ppf(<span class="fl">0.975</span>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="co">#z = 1.96</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the margin of error</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>moE <span class="op">=</span> z <span class="op">*</span> se</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the confidence interval</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="op">=</span> (p1 <span class="op">-</span> p2) <span class="op">-</span> moE</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>ci_upper <span class="op">=</span> (p1 <span class="op">-</span> p2) <span class="op">+</span> moE</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a><span class="co">#ci_lower = 0.18 - moE</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="co">#ci_upper = 0.18 + moE</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>round_values([p1 <span class="op">-</span> p2, p1, p2, z,moE, ci_lower, ci_upper], <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>[0.1812, 0.5496, 0.3684, 1.96, 0.0677, 0.1135, 0.2489]</code></pre>
</div>
</div>
<p>Interpreting the Confidence Interval “range of reasonable values for our parameter” With 95% confidence, the population proportion of parents with white children who have taken swimming lessons is 11.35 to 24.89% higher than the population proportion of parents with black children who have taken swimming lessons.</p>
</section>
</section>
</section>
<section id="population-means" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Population Means</h1>
<section id="one-mean" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="one-mean"><span class="header-section-number">3.1</span> One Mean</h2>
<p><span class="math display">\[
\bar{x} \pm t^* \left(\frac{s}{\sqrt{n}}\right)
\]</span></p>
<p>Mean = 82.48 inches</p>
<p>Standard Deviation = 15.06 inches</p>
<p><span class="math inline">\(n\)</span> = 25 observations &gt; <span class="math inline">\(t*\)</span> = 2.064</p>
<p><span class="math display">\[
\begin{align*}
\bar{x} \pm t^* \left( \frac{s}{\sqrt{n}} \right) &amp;= 82.48 \pm 2.064 \left( \frac{15.06}{\sqrt{25}} \right) \\
&amp;= 82.48 \pm 2.064(3.012) \\
&amp;= 82.48 \pm 6.22 \\
&amp; \text{(76.26 inches, 88.70 inches)}
\end{align*}
\]</span></p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your confidence level and degrees of freedom</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">25</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="op">=</span> <span class="fl">0.95</span>  <span class="co"># for a 95% confidence interval</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>degrees_of_freedom <span class="op">=</span> sample_size <span class="op">-</span> <span class="dv">1</span>  <span class="co"># degrees of freedom</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the t-score</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># The ppf function returns the inverse of the CDF (Cumulative Distribution Function)</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># The argument for the ppf function should be 1 minus half of the alpha level (1 - alpha/2)</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># because the t-distribution is symmetric, and we want the cumulative area from -t to t.</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>t_score <span class="op">=</span> t.ppf((<span class="dv">1</span> <span class="op">+</span> confidence_level) <span class="op">/</span> <span class="dv">2</span>, degrees_of_freedom)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="co">#t_score = 2.064</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-score for </span><span class="sc">{</span>confidence_level<span class="op">*</span><span class="dv">100</span><span class="sc">}</span><span class="ss">% confidence level and </span><span class="sc">{</span>degrees_of_freedom<span class="sc">}</span><span class="ss"> degrees of freedom: </span><span class="sc">{</span>t_score<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t-score for 95.0% confidence level and 24 degrees of freedom: 2.0638985616280205</code></pre>
</div>
</div>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Given values for the mean, t-score, standard deviation, and sample size</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>mean <span class="op">=</span> <span class="fl">82.48</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>standard_deviation <span class="op">=</span> <span class="fl">15.06</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the margin of error</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>margin_of_error <span class="op">=</span> t_score <span class="op">*</span> (standard_deviation <span class="op">/</span> (sample_size <span class="op">**</span> <span class="fl">0.5</span>))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the confidence interval</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="op">=</span> mean <span class="op">-</span> margin_of_error</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="op">=</span> mean <span class="op">+</span> margin_of_error</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Margin of Error: </span><span class="sc">{</span>margin_of_error<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean (95% CI): </span><span class="sc">{</span>mean<span class="sc">:.2f}</span><span class="ss"> (</span><span class="sc">{</span>lower_bound<span class="sc">:.2f}</span><span class="ss"> to </span><span class="sc">{</span>upper_bound<span class="sc">:.2f}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Margin of Error: 6.22
Mean (95% CI): 82.48 (76.26 to 88.70)</code></pre>
</div>
</div>
</section>
<section id="mean-difference-for-paired-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="mean-difference-for-paired-data"><span class="header-section-number">3.2</span> Mean Difference for Paired Data</h2>
<blockquote class="blockquote">
<p>Difference = older twin - younger twin<br>
Difference in Twin Education<br>
n = 340 observations<br>
Minimum = -3.5 years<br>
Maximum = 4 years<br>
72.1% had a difference of 0 years<br>
Mean = 0.0838 years<br>
Standard Deviation = 0.7627 years</p>
</blockquote>
<blockquote class="blockquote">
<p>95% Confidence Interval Calculations<br>
Best Estimate + Margin of Error<br>
Sample mean difference + “a few” . estimated standard error<br>
t*<br>
t* multiplier comes from a t-distribution with n - 1 degrees of freedom<br>
95% confidence<br>
n= 25 &gt; t* = 2.064<br>
n= 1000 &gt; t* = 1.962</p>
</blockquote>
<p><span class="math display">\[\begin{align*}
\text{Sample mean difference} \ \bar{x}_d \pm t^* \left( \frac{s_d}{\sqrt{n}} \right) &amp; \\
\text{For } n = 25, \ t^* = 2.064 \ \text{, so we have:} &amp; \\
\bar{x}_d \pm 2.064 \left( \frac{s_d}{\sqrt{25}} \right) &amp; \\
\text{If } \bar{x}_d = 82.48 \ \text{and} \ s_d = 15.06, \ \text{then:} &amp; \\
82.48 \pm 2.064 \left( \frac{15.06}{\sqrt{25}} \right) &amp; \\
82.48 \pm 2.064 \times 3.012 &amp; \\
82.48 \pm 6.22 &amp;
\end{align*}\]</span></p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Given values</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">25</span>  <span class="co"># Sample size</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="op">=</span> <span class="fl">0.95</span>  <span class="co"># Confidence level</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>s_d <span class="op">=</span> <span class="fl">15.06</span>  <span class="co"># Standard deviation of the differences</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>x_d_bar <span class="op">=</span> <span class="fl">82.48</span>  <span class="co"># Difference in sample means</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the t-score</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>degrees_of_freedom <span class="op">=</span> n <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>t_score <span class="op">=</span> t.ppf((<span class="dv">1</span> <span class="op">+</span> confidence_level) <span class="op">/</span> <span class="dv">2</span>, degrees_of_freedom)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error of the mean difference</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>se_d <span class="op">=</span> s_d <span class="op">/</span> np.sqrt(n)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the margin of error</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>margin_of_error <span class="op">=</span> t_score <span class="op">*</span> se_d</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the confidence interval</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="op">=</span> x_d_bar <span class="op">-</span> margin_of_error</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="op">=</span> x_d_bar <span class="op">+</span> margin_of_error</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results in a publication-friendly format</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample Mean Difference: </span><span class="sc">{</span>x_d_bar<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Margin of Error: </span><span class="sc">{</span>margin_of_error<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% Confidence Interval: (</span><span class="sc">{</span>lower_bound<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>upper_bound<span class="sc">:.2f}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample Mean Difference: 82.48
Margin of Error: 6.22
95% Confidence Interval: (76.26, 88.70)</code></pre>
</div>
</div>
<p><span class="math display">\[\begin{align*}
\text{Mean Difference Confidence Interval} \\
\text{Mean} &amp;= 0.084 \text{ years} \\
\text{Standard Deviation} &amp;= 0.76 \text{ years} \\
n &amp;= 340 \text{ observations} \rightarrow t^* = 1.967 \\
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
\bar{x}_d \pm t^* \left( \frac{s_d}{\sqrt{n}} \right) &amp;= 0.084 \pm 1.967 \left( \frac{0.76}{\sqrt{340}} \right) \\
&amp;= 0.084 \pm 1.967 (0.04) \\
&amp;= 0.084 \pm 0.0814 \\
&amp;= (0.0026, 0.1654) \text{ years}
\end{align*}\]</span></p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Given values from the image</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>mean_diff <span class="op">=</span> <span class="fl">0.084</span>  <span class="co"># Mean difference (x̄_d)</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>std_dev_diff <span class="op">=</span> <span class="fl">0.76</span>  <span class="co"># Standard deviation of differences (s_d)</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">340</span>  <span class="co"># Sample size (n)</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="op">=</span> <span class="fl">0.95</span>  <span class="co"># Confidence level for 95%</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the t-score using the degrees of freedom (n - 1)</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>degrees_of_freedom <span class="op">=</span> n <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co">#t_score = t.ppf((1 + confidence_level) / 2, degrees_of_freedom)</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>t_score <span class="op">=</span> <span class="fl">1.967</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error of the mean difference</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>standard_error_diff <span class="op">=</span> std_dev_diff <span class="op">/</span> np.sqrt(n)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the margin of error</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>margin_of_error <span class="op">=</span> t_score <span class="op">*</span> standard_error_diff</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the confidence interval</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="op">=</span> mean_diff <span class="op">-</span> margin_of_error</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="op">=</span> mean_diff <span class="op">+</span> margin_of_error</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample Mean Difference: </span><span class="sc">{</span>mean_diff<span class="sc">}</span><span class="ss"> years"</span>)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Margin of Error: </span><span class="sc">{</span>margin_of_error<span class="sc">:.4f}</span><span class="ss"> years"</span>)</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% Confidence Interval: (</span><span class="sc">{</span>lower_bound<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>upper_bound<span class="sc">:.4f}</span><span class="ss">) years"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample Mean Difference: 0.084 years
Margin of Error: 0.0811 years
95% Confidence Interval: (0.0029, 0.1651) years</code></pre>
</div>
</div>
<p>With 95% confidence, the population mean difference of the older twin’s less the younger twin’s self-reported education is estimated to be between lower_bound years and upper_bound years.</p>
<section id="using-scipy-and-statsmodels" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="using-scipy-and-statsmodels"><span class="header-section-number">3.2.1</span> Using SciPy and StatsModels</h3>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.stats.api <span class="im">as</span> sms</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Given values from the image</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>mean_diff <span class="op">=</span> <span class="fl">0.084</span>  <span class="co"># Mean difference (x̄_d)</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>std_dev_diff <span class="op">=</span> <span class="fl">0.76</span>  <span class="co"># Standard deviation of differences (s_d)</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">340</span>  <span class="co"># Sample size (n)</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="op">=</span> <span class="fl">0.95</span>  <span class="co"># Confidence level for 95%</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error of the mean difference</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>standard_error_diff <span class="op">=</span> std_dev_diff <span class="op">/</span> np.sqrt(n)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Using SciPy to calculate the confidence interval</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>ci_low, ci_up <span class="op">=</span> stats.t.interval(confidence_level, df<span class="op">=</span>n<span class="op">-</span><span class="dv">1</span>, loc<span class="op">=</span>mean_diff, scale<span class="op">=</span>standard_error_diff)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Using StatsModels to calculate the confidence interval</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>cm <span class="op">=</span> sms.CompareMeans(sms.DescrStatsW(np.random.normal(mean_diff, std_dev_diff, n)), </span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>                      sms.DescrStatsW(np.random.normal(mean_diff, std_dev_diff, n)))</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>ci_low_sms, ci_up_sms <span class="op">=</span> cm.tconfint_diff(usevar<span class="op">=</span><span class="st">'unequal'</span>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Confidence Interval using SciPy: (</span><span class="sc">{</span>ci_low<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci_up<span class="sc">:.4f}</span><span class="ss">) years"</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Confidence Interval using StatsModels: (</span><span class="sc">{</span>ci_low_sms<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci_up_sms<span class="sc">:.4f}</span><span class="ss">) years"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confidence Interval using SciPy: (0.0029, 0.1651) years
Confidence Interval using StatsModels: (-0.2004, 0.0357) years</code></pre>
</div>
</div>
<p>The SciPy and StatsModels libraries might give different confidence intervals (CIs) due to the way they handle the data and calculations internally, particularly if they’re using different assumptions or default parameters in their calculations. Here are a few reasons why differences might arise:</p>
<ol type="1">
<li><p><strong>Underlying Assumptions</strong>: StatsModels might use a different method to estimate the variance (e.g., assuming equal or unequal variances in two samples when calculating confidence intervals for mean differences).</p></li>
<li><p><strong>Data Handling</strong>: The snippet provided uses simulated data for StatsModels, which could introduce variability. Normally, you would use actual data rather than simulated data to ensure consistency.</p></li>
<li><p><strong>Defaults for Degrees of Freedom</strong>: The method of calculating degrees of freedom may vary. Some methods adjust degrees of freedom based on sample size and variance, particularly in the case of two independent samples with potentially unequal variances.</p></li>
<li><p><strong>Numerical Precision</strong>: Differences in numerical precision can result from the specific algorithms used to calculate the t-scores and the standard error within each package.</p></li>
<li><p><strong>Confidence Interval Estimation</strong>: Some statistical packages might use a slightly different formula or method to calculate the confidence interval. For example, StatsModels provides several ways to calculate the confidence interval for the mean difference, including assuming equal variances (<code>usevar='pooled'</code>) or not (<code>usevar='unequal'</code>).</p></li>
</ol>
<p>To ensure consistency, it’s important to use the same dataset and understand the default behaviors and assumptions of the statistical functions you are using. If precise control over the calculation method is required, you should manually specify the parameters to match your statistical model’s assumptions.</p>
</section>
</section>
<section id="estimating-a-difference-in-population-means-for-independent-groups" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="estimating-a-difference-in-population-means-for-independent-groups"><span class="header-section-number">3.3</span> Estimating a Difference in Population Means for Independent Groups</h2>
<p>Here are the steps to estimate a difference in population means with confidence for two independent groups:</p>
<ol type="1">
<li><strong>Identify the Populations and Parameter of Interest</strong>:
<ul>
<li>Specify the populations you are comparing (e.g., Mexican-American adults aged 18 to 29 living in the United States).</li>
<li>Define the parameter of interest (e.g., BMI measured in kilograms per meter squared).</li>
<li>Use symbols $ _1 $ and $ _2 $ to represent the means of the two populations, and focus on the difference $ _1 - _2 $.</li>
</ul></li>
<li><strong>Collect Samples and Calculate Descriptive Statistics</strong>:
<ul>
<li>Sample the two populations separately according to the characteristic of interest (e.g., gender from the NHANES dataset).</li>
<li>Calculate the mean, standard deviation, minimum, maximum, and sample size for both sub-groups.</li>
</ul></li>
<li><strong>Understand the Distribution of Sample Mean Differences</strong>:
<ul>
<li>Recognize that the sample mean will vary from sample to sample, creating a sampling distribution.</li>
<li>Note that if both population responses are approximately normal or sample sizes are large, the distribution of the difference in sample means will be approximately normal.</li>
</ul></li>
<li><strong>Estimate the Standard Error</strong>:
<ul>
<li>Acknowledge that we often don’t know true population variances, so we estimate them using sample variances.</li>
<li>Use the formula for standard error involving the sample standard deviations and sizes of both groups.</li>
</ul></li>
<li><strong>Construct the Confidence Interval</strong>:
<ul>
<li>Start with the difference in sample means as the best estimate.</li>
<li>Add and subtract the margin of error, which is a multiple of the estimated standard error.</li>
<li>Use a t-score multiplier from the t-distribution corresponding to the desired confidence level.</li>
</ul></li>
<li><strong>Choose the Correct Approach—Pooled or Unpooled</strong>:
<ul>
<li>If population variances are assumed to be equal, use the pooled approach; otherwise, use the unpooled approach.</li>
<li>For the pooled approach, combine the variances of the two samples.</li>
<li>For the unpooled approach, keep the variances separate.</li>
</ul></li>
<li><strong>Interpret the Confidence Interval</strong>:
<ul>
<li>Understand that the interval provides a range of reasonable values for the parameter of interest.</li>
<li>The confidence level indicates the proportion of such intervals that would contain the true population mean difference if the procedure were repeatedly applied.</li>
</ul></li>
<li><strong>Verify Assumptions</strong>:
<ul>
<li>Ensure both samples are simple random samples and independent of each other.</li>
<li>Check for normality using graphical methods like histograms and Q-Q plots.</li>
<li>Apply the Central Limit Theorem if sample sizes are large to justify normality.</li>
</ul></li>
<li><strong>Decide on Variance Equality</strong>:
<ul>
<li>Inspect sample variances and interquartile ranges to assess whether population variances can be assumed equal.</li>
<li>Choose the pooled method if variances are similar, or the unpooled method if not.</li>
</ul></li>
<li><strong>Calculate and Interpret the Final Confidence Interval</strong>:
<ul>
<li>Use the chosen method to calculate the confidence interval for the difference in population means.</li>
<li>Communicate the results, stating the range and confidence level clearly.</li>
</ul></li>
</ol>
<p>Each of these steps provides the framework for estimating the difference in population means with confidence, ensuring a robust statistical analysis of two independent groups.</p>
<p>The image you’ve uploaded appears to contain a slide from a presentation that outlines a research question. It reads:</p>
<hr>
<section id="research-question" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="research-question"><span class="header-section-number">3.3.1</span> Research Question</h3>
<p>Considering Mexican-American adults (ages 18 - 29) living in the United States, do males and females differ significantly in mean Body Mass Index (BMI)?</p>
<ul>
<li>Population: Mexican-American adults (ages 18 - 29) in the U.S.</li>
<li>Parameter of Interest (μ1 - μ2): Body Mass Index or BMI (kg/m²)</li>
</ul>
<hr>
<p>To address this research question, we would typically follow a series of steps:</p>
<ol type="1">
<li><p><strong>Hypothesis Formulation</strong>: Based on the parameter of interest, which is the difference in mean BMI between males (μ1) and females (μ2), we would set up the null hypothesis (H0: μ1 - μ2 = 0) indicating no difference and the alternative hypothesis (H1: μ1 - μ2 ≠ 0) indicating a significant difference.</p></li>
<li><p><strong>Data Collection</strong>: Gather a representative sample of Mexican-American adults, ensuring a balanced representation of males and females aged 18-29.</p></li>
<li><p><strong>Data Analysis</strong>: Calculate the mean BMI for both groups and perform a hypothesis test, such as an independent t-test, to evaluate the difference in means.</p></li>
<li><p><strong>Result Interpretation</strong>: Determine if the observed difference is statistically significant based on the p-value and the pre-determined level of significance (commonly α = 0.05).</p></li>
<li><p><strong>Conclusion</strong>: Draw conclusions from the statistical analysis and relate them back to the research question.</p></li>
</ol>
<p>If we have access to a dataset containing the relevant information, I can assist with the Python code to perform the necessary statistical analysis. Please let me know if you would like to proceed with this, or if there is another aspect of this research question you would like to explore.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Import necessary libraries</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Load your dataset</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming you have a CSV file named 'data.csv' with columns 'age', 'gender', 'bmi'</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># data = pd.read_csv('path_to_your_data.csv')</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># For demonstration purposes, let's create a mock DataFrame</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace this mock data with your actual data</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.DataFrame({</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'age'</span>: [<span class="dv">18</span>, <span class="dv">20</span>, <span class="dv">29</span>] <span class="op">*</span> <span class="dv">20</span>,  <span class="co"># Mock ages</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'gender'</span>: [<span class="st">'male'</span>, <span class="st">'female'</span>] <span class="op">*</span> <span class="dv">30</span>,  <span class="co"># Mock genders</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'bmi'</span>: np.random.normal(<span class="dv">25</span>, <span class="dv">5</span>, <span class="dv">60</span>)  <span class="co"># Mock BMIs with a mean of 25 and std dev of 5</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Clean and format the data if necessary</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure that the 'gender' column is categorized properly</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'gender'</span>] <span class="op">=</span> data[<span class="st">'gender'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the dataset for the age range 18-29</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data[(data[<span class="st">'age'</span>] <span class="op">&gt;=</span> <span class="dv">18</span>) <span class="op">&amp;</span> (data[<span class="st">'age'</span>] <span class="op">&lt;=</span> <span class="dv">29</span>)]</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Separate the data into two groups</span></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>male_bmi <span class="op">=</span> data[data[<span class="st">'gender'</span>] <span class="op">==</span> <span class="st">'male'</span>][<span class="st">'bmi'</span>]</span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>female_bmi <span class="op">=</span> data[data[<span class="st">'gender'</span>] <span class="op">==</span> <span class="st">'female'</span>][<span class="st">'bmi'</span>]</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Calculate the mean BMI for each group</span></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>mean_male_bmi <span class="op">=</span> male_bmi.mean()</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a>mean_female_bmi <span class="op">=</span> female_bmi.mean()</span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Perform an independent t-test</span></span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a>t_stat, p_value <span class="op">=</span> stats.ttest_ind(male_bmi, female_bmi)</span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the results</span></span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean BMI for males: </span><span class="sc">{</span>mean_male_bmi<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean BMI for females: </span><span class="sc">{</span>mean_female_bmi<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"T-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P-value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Based on the p-value, determine if the result is statistically significant</span></span>
<span id="cb31-42"><a href="#cb31-42" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span>  <span class="co"># Common significance level</span></span>
<span id="cb31-43"><a href="#cb31-43" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> p_value <span class="op">&lt;</span> alpha:</span>
<span id="cb31-44"><a href="#cb31-44" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"We reject the null hypothesis, suggesting a significant difference in BMI between genders."</span>)</span>
<span id="cb31-45"><a href="#cb31-45" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb31-46"><a href="#cb31-46" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"We fail to reject the null hypothesis, suggesting no significant difference in BMI between genders."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean BMI for males: 25.46
Mean BMI for females: 26.24
T-statistic: -0.67
P-value: 0.5061
We fail to reject the null hypothesis, suggesting no significant difference in BMI between genders.</code></pre>
</div>
</div>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming you have a DataFrame 'data' with 'gender' and 'bmi' columns</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))  <span class="co"># Set the figure size</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>boxplot <span class="op">=</span> data.boxplot(column<span class="op">=</span><span class="st">'bmi'</span>, by<span class="op">=</span><span class="st">'gender'</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'BMI Distribution by Gender'</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">''</span>)  <span class="co"># Suppress the default title</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Gender'</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'BMI'</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 800x600 with 0 Axes&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="PyStats_files/figure-html/cell-19-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot with Seaborn</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'gender'</span>, y<span class="op">=</span><span class="st">'bmi'</span>, data<span class="op">=</span>data)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'BMI Distribution by Gender'</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Gender'</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'BMI'</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="PyStats_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters for the sampling distribution</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># For demonstration, we assume the following:</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The difference in population means is 0 under the null hypothesis</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>mu_diff <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of the sampling distribution, assumed to be 1 for this example</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>sigma_diff <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size for illustration</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a sampling distribution of the difference in means</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>sample_diff_means <span class="op">=</span> np.random.normal(mu_diff, sigma_diff, sample_size)</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the distribution</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>plt.hist(sample_diff_means, bins<span class="op">=</span><span class="dv">30</span>, density<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'b'</span>)</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the normal distribution curve</span></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>xmin, xmax <span class="op">=</span> plt.xlim()</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(xmin, xmax, <span class="dv">100</span>)</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> norm.pdf(x, mu_diff, sigma_diff)</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>plt.plot(x, p, <span class="st">'k'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>title <span class="op">=</span> <span class="st">"Sampling Distribution of the Difference in Two Independent Sample Means"</span></span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>plt.title(title)</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Difference in sample means'</span>)</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="PyStats_files/figure-html/cell-21-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The graph above illustrates the sampling distribution of the difference in two independent sample means. It shows a normal distribution centered around zero, which is what we’d expect under the null hypothesis that there is no difference between the two population means (<span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>).</p>
<p>The histogram represents the frequency of various differences observed in the sample means, while the black curve is the probability density function of a normal distribution with the mean (<span class="math inline">\(\mu_{diff}\)</span>) set to 0 and a standard deviation (<span class="math inline">\(\sigma_{diff}\)</span>) assumed to be 1 for this example. This visual representation helps us understand the variability we might expect by chance when estimating the difference between two means from independent samples.</p>
<p>In the context of a real-world application, such as comparing BMI between genders, you would calculate the actual standard deviation of the sampling distribution based on the sample data and the sample sizes of the groups being compared. This would then inform your hypothesis testing, allowing you to determine the likelihood of observing the sample mean difference if the null hypothesis were true.</p>
<p>The image you’ve uploaded depicts a concept from inferential statistics known as the “Sampling Distribution of the Difference in Two (Independent) Sample Means”. This concept is pivotal when comparing the means from two independent groups to determine if there is a statistically significant difference between them.</p>
<p>The key points outlined in the image are:</p>
<ol type="1">
<li>If both populations of responses have distributions that are approximately normal, or if the sample sizes are large enough, then the distribution of the difference in sample means is also approximately normal.</li>
<li>The center of this sampling distribution is at the difference in population means <span class="math inline">\(\mu_1 - \mu_2\)</span>.</li>
<li>The distribution allows for the calculation of the probability of observing a sample mean difference as extreme as, or more extreme than, the one observed.</li>
</ol>
<p>In the context of the previous discussion about BMI across genders, the sampling distribution would be used to estimate the likelihood of observing the difference in mean BMIs between males and females under the null hypothesis that there is no true difference in the population means.</p>
<p>Calculation of the standard error for the sampling distribution of the difference between two independent sample means. The standard error is a measure of the variability of the sampling distribution and is crucial when conducting hypothesis tests or constructing confidence intervals.</p>
<p>The standard error formula for the difference between two independent means is provided in the image as:</p>
<p><span class="math inline">\(SE = \sqrt{\frac{{\sigma_1}^2}{n_1} + \frac{{\sigma_2}^2}{n_2}}\)</span></p>
<p>Where: - <span class="math inline">\(\sigma_1^2\)</span> and <span class="math inline">\(\sigma_2^2\)</span> are the population variances of the first and second groups, respectively. - <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are the sample sizes of the first and second groups, respectively.</p>
<p>Since population variances are rarely known, we use sample variances <span class="math inline">\(s_1^2\)</span> and <span class="math inline">\(s_2^2\)</span> to estimate the standard error:</p>
<p><span class="math inline">\(Estimated\:SE = \sqrt{\frac{{s_1}^2}{n_1} + \frac{{s_2}^2}{n_2}}\)</span></p>
<p>This estimated standard error is used to calculate test statistics like the t-statistic in an independent samples t-test, or to construct confidence intervals for the difference between the two means.</p>
<p>Would you like to see how to calculate this estimated standard error using Python, given sample data?</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Given values</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="op">=</span> <span class="dv">100</span>  <span class="co"># The sample mean (x̄)</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>pop_std <span class="op">=</span> <span class="dv">15</span>       <span class="co"># Population standard deviation (σ)</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">50</span>             <span class="co"># Sample size (n)</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>confidence_level <span class="op">=</span> <span class="fl">0.95</span>  <span class="co"># Confidence level</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the z-score for the given confidence level</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> stats.norm.ppf((<span class="dv">1</span> <span class="op">+</span> confidence_level) <span class="op">/</span> <span class="dv">2</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error of the mean (SEM)</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>sem <span class="op">=</span> pop_std <span class="op">/</span> np.sqrt(n)</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the margin of error (MOE)</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>moe <span class="op">=</span> z_score <span class="op">*</span> sem</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the confidence interval</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="op">=</span> sample_mean <span class="op">-</span> moe</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>ci_upper <span class="op">=</span> sample_mean <span class="op">+</span> moe</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>(ci_lower, ci_upper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>(95.84228852695097, 104.15771147304903)</code></pre>
</div>
</div>
<p>There are two different approaches to constructing confidence intervals when dealing with two populations:</p>
<ol type="1">
<li><p><strong>Pooled Approach</strong>: This method assumes that the variances of the two populations are equal. Mathematically, this is denoted as $ _1^2 = _2^2 $, where $ _1^2 $ and $ _2^2 $ represent the population variances of the first and second populations, respectively.</p></li>
<li><p><strong>Unpooled Approach</strong>: This method does not assume that the variances of the two populations are equal. It is used when the assumption of equal variances (homogeneity of variance) is not tenable.</p></li>
</ol>
<p>When calculating a confidence interval for the difference between two means, the choice between a pooled and unpooled approach depends on the results of a test for equal variances (such as Levene’s test or an F-test). If the test suggests that the variances are equal, a pooled approach is typically used, which leads to a simpler formula and a more precise confidence interval. If the variances are not equal, the unpooled approach is used, which adjusts the degrees of freedom and the standard error to account for the difference in variance.</p>
<p>To translate these statistical approaches into practical application, if you provide data or require further elaboration on how these methods are implemented in statistical analysis, I can demonstrate that with appropriate Python code or further explanation.</p>
<p>The image you have uploaded appears to show a slide from a statistical presentation on how to calculate unpooled confidence intervals for the difference between two sample means. The formula provided is the standard formula for an unpooled (also known as Welch’s) t-confidence interval, which is used when the two populations are assumed to have unequal variances.</p>
<p>The formula for the confidence interval is given by:</p>
<p><span class="math display">\[
(\bar{x}_1 - \bar{x}_2) \pm t^* \cdot \sqrt{\frac{{s_1}^2}{n_1} + \frac{{s_2}^2}{n_2}}
\]</span></p>
<p>Here, <span class="math inline">\(\bar{x}_1\)</span> and <span class="math inline">\(\bar{x}_2\)</span> are the sample means, <span class="math inline">\(s_1^2\)</span> and <span class="math inline">\(s_2^2\)</span> are the sample variances, <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are the sample sizes, and <span class="math inline">\(t^*\)</span> is the t-score from the t-distribution that corresponds to the desired confidence level.</p>
<p>The degrees of freedom (<span class="math inline">\(df\)</span>) for the <span class="math inline">\(t^*\)</span> multiplier can be found using Welch’s approximation. If technology to calculate this is not available, the slide suggests a conservative approach can be taken by using the smaller of <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span> (i.e., <span class="math inline">\(df = \min(n_1 - 1, n_2 - 1)\)</span>).</p>
</section>
</section>
</section>
<section id="end" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> End</h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>